### ISSUE TITLE
submitReportToServer.js error when POSTing to an SSL'd Server

### ISSUE THREAD

**Issue by davidheerema** [cds-snc/report-a-cybercrime#1868]
## Summary 📋 

> Modifying this line to post to something like https://{serverURL}:443 or https://{serverURL} will produce an error and not POST.

https://github.com/cds-snc/report-a-cybercrime/blob/3ad44c5ce0647f62f232e95b41acbb1b9f8bf28a/f2/src/utils/submitReportToServer.js#L31

## Steps to Reproduce ⌨️ 

> Edit the file to post to an SSL-enabled endpoint then run `node submitReportToServer.js`

## Error Example 📛 

> PS /Users/david/Documents/GitHub/report-a-cybercrime/f2/src/utils> node submitReportToServer.js
(node:43439) UnhandledPromiseRejectionWarning: FetchError: request to https://report-dev.con.rcmp-grc.gc.ca:443/submit failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/david/Documents/GitHub/report-a-cybercrime/f2/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:197:13)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
(node:43439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by davidheerema** [comment]
From @sdzhangtao 

I know this problem in java. It's always the certificate store problem. But in NodeJS. A google search said, you need to add the following:
require('https').globalAgent.options.ca = require('ssl-root-cas/latest').create();

https://www.npmjs.com/package/ssl-root-cas

Maybe because Azure SSL is using the cheap, free Let's Encrypt?

**Comment by davidheerema** [comment]
This issue is no longer an issue - I have corrected the mistake in the TLS certificates and chained them correctly.
